name: Build and Push Docker Image

on:
  push:
    branches:
      - base
      - main

jobs:
  # Build Docker Image on the "base" branch
  build-base:
    if: github.ref_name == 'base'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t searxng:base .
        env:
          DOCKER_BUILDKIT: 1

  # Build and Push Docker Image on the "main" branch
  build-and-push-main:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and Push Docker Images
        run: |
          # Push to Docker Hub
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            -t chpeerapat/searxng:latest .

          # Push to GitHub Container Registry
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            -t ghcr.io/chinpeerapat/searxng-simple-setting/searxng:latest .
        env:
          DOCKER_BUILDKIT: 1
