name: Build and Push Docker Images

on:
  push:
    branches:
      - base
      - main

jobs:
  # Build and Push the Base Image
  build-and-push-base:
    if: github.ref_name == 'base' || github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: base  # Always use the 'base' branch for the base image

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and Push Base Docker Image
        run: |
          # Build and push the base image to Docker Hub
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            -t chpeerapat/searxng:base \
            .

          # Build and push the base image to GHCR
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            -t ghcr.io/chinpeerapat/searxng-simple-setting:base \
            .
        env:
          DOCKER_BUILDKIT: 1

  # Build and Push the Main Image
  build-and-push-main:
    needs: build-and-push-base
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main  # Use the 'main' branch for the main image

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and Push Main Docker Image
        run: |
          # Build and push the main image to Docker Hub
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg BASE_IMAGE=chpeerapat/searxng:base \
            --push \
            -t chpeerapat/searxng:main \
            .

          # Build and push the main image to GHCR
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg BASE_IMAGE=ghcr.io/chinpeerapat/searxng-simple-setting:base \
            --push \
            -t ghcr.io/chinpeerapat/searxng-simple-setting:main \
            .
        env:
          DOCKER_BUILDKIT: 1
