name: Build and Push Docker Image

on:
  push:
    branches:
      - base
      - main

jobs:
  # Build and Push the Base Image
  build-and-push-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Base Docker Image
        run: |
          # Build the base image
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            -t chpeerapat/searxng:base \
            .
        env:
          DOCKER_BUILDKIT: 1

  # Build and Push the Main Image (depends on the Base Image)
  build-and-push-main:
    needs: build-and-push-base
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and Push Main Docker Image
        run: |
          # Build the main image using the base image
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg BASE_IMAGE=chpeerapat/searxng:base \
            --push \
            -t chpeerapat/searxng:main \
            -t ghcr.io/chinpeerapat/searxng-simple-setting:main \
            .
        env:
          DOCKER_BUILDKIT: 1
